### ISSUE TITLE
Cannot create e-invoice after installed Edi Route Add-on

### ISSUE THREAD

**Issue by felixsniper** [vertelab/odoo-edi#67]
Hi Vertelab,

I tried to install Edi Route and Edi Peppol on Odoo CE V12.
But I failed to create an invoice after install these module, it showed an error dialog like this.

![image](https://user-images.githubusercontent.com/69030714/100094223-40f40d80-2e8b-11eb-82bd-f0cd46f84e8e.png)

Log: 
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 136, in create_invoices
    sale_orders.action_invoice_create()
  File "/usr/lib/python3/dist-packages/odoo/addons/edi_route_sale/sale.py", line 114, in action_invoice_create
    res =  super(sale_order,self).action_invoice_create(grouped=grouped, states=states, date_invoice = date_invoice)
TypeError: action_invoice_create() got an unexpected keyword argument 'states'

Please help give me an advice,
Thanks and Regards, 
Felix Nguyen

**Comment by FredrikArvas** [comment]
Hi Felix

Great to hear from you!
Could you give me a call in order for me to better understand your environment.
Det går bra på svenska: 
+46708145595
/Fredrik

**Comment by FredrikArvas** [comment]
Hi again @felixdsniper 
Great to hear from you!
Could you give me a call in order for me to better understand your environment.
Det går bra på svenska:
+46708145595
/Fredrik
